config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  get  '/blogs/:blog_id/comments', to: 'comments#show'
  resources :blogs do
    resources :comments
  end 

  namespace :venblog do
    resources :blogs #, only: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :comments, dependent: :destroy

  validates :title, :shortdescription, :description, presence: true
  validates :title,
    :presence => true,
    :length => { :maximum => 100 }

  validates :shortdescription,
    :presence => true,
    :length => { :maximum => 300 }

  validates :description,
    :presence => true,
    :length => { :maximum => 500 }

  validates :description,
    :presence => true,
    :length => { :maximum => 500 }

  # validates :image_size, presence: true

  default_scope {order(created_at: :desc)}
  scope :unpublished, -> { where(published: false) }
  scope :published, -> { where(published: true) }
  scope :description_includes, ->(keyword) { where("description LIKE ?", "%#{keyword}%") }

  def image_size
    if (image.size > 1.megabytes)
      errors.add(:image, "Image size within 1 megabytes")
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog

  validates :comment, :Name, presence: true
  validates :comment, length: { maximum: 300 }
  validates :Name, length: { maximum:100 }

  scope :newest_first, -> { order(created_at: :desc) }

end

app/models/top.rb
class TopController < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5 }
  validates :image, presence: true
  # Scopes
  default_scope {order(created_at: :desc)}
  scope :published, -> { where(published: true) }
  scope :unpublished, -> { where(published: false) }
  scope :description_includes, ->(keyword) { where("description LIKE ?", "%#{keyword}%") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @blog = Blog.find_by(id: params[:blog_id])
    @comment = @blog.comments.new
    # @comments = @blog.comments
    @comments_all = Comment.all
    @comments = @comments_all.order(created_at: :desc).page(params[:page].to_i).per(20)
    @comments_blog = @blog.comments.all
  end

  def show
    @blog = Blog.find_by(id: params[:blog_id])
    # @comment = @blog.comments.find(params[:id])
    @comments = @blog.comments
    # @comments = comments #.order(created_at: :desc).page(params[:page].to_i).per(20)
    @comments_all = Comment.all
    @comments = @comments_all.order(created_at: :desc).page(params[:page].to_i).per(20)
    @comments_blog = @blog.comments.all
  end

  def create
    @blog = Blog.find_by(id: params[:blog_id])
    @comment = @blog.comments.create(comment_params)
    if @comment.save
      flash[:notice] = 'You have successfully created the comment'
      redirect_to venblog_blog_path(@blog.id)
    else
      flash.now[:notice] = 'There is an error in your form'
      # redirect_to blog_path(@blog.id)
    end
  end

 # private

  # Use callbacks to share common setup or constraints between actions.

  def comment_params
    params.require(:comment).permit(:Name, :comment)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  # GET /blogs or /blogs.json
  def index
    @blogs = if params[:keyword]
      Blog.where("title like ?", "%#{params[:keyword]}%")
    else
      Blog.all
    end
    # @blog = Blog.find(params[:blog_id])
    # @comment = @blog.comment #.find(params[:id])
    @blogs = @blogs.published
    @lastest_blogs = Blog.published.order(created_at: :desc).limit(5)
    @blogs_all = @blogs.order(created_at: :desc).page(params[:page].to_i).per(20)
    # avoid n+1
    @comments = Comment.order(created_at: :desc).includes(:blog).limit(5)
  end

  def show
    @blog = Blog.find_by(id: params[:blog_id])
    @comment = @blog.comments.find(params[:comment].permit(:Name, :comment))
  end

  private

  def comment_params
    params.require(:comment).permit(:Name, :comment)
  end

  def blog_params
    params.require(:blog).permit(:title, :shortdescription, :description, :published, :image)
  end
end

app/controllers/venblog/blogs_controller.rb
module Venblog
  class BlogsController < ApplicationController
    before_action :set_blog, only: %i[show edit update destroy]
    # GET /blogs or /blogs.json

    def index
      @blogs = if params[:keyword]
                Blog.where('title like ?', "%#{params[:keyword]}%")
              else
                Blog.all
              end
      @lastest_blogs = Blog.order(created_at: :desc).limit(5)
      @blogs_all = @blogs.order(created_at: :desc).page(params[:page].to_i).per(20)
      @comments = Comment.order(created_at: :desc).limit(5)
    end

    # GET /blogs/1
    def show
      @blog = Blog.find(params[:id])
      if @blog.published
      else
        flash[:notice] = 'This page is unpublished'
        redirect_to blog_comments_path(@blog)
      end
      # @blog_published = @blog.where(published: true)
      # @blog_unpublished = @blog.where(published: false)
      @comment = Blog.new
      @comments = @blog.comments.order(created_at: :desc).page(params[:page].to_i).per(20)
      @comments_blog = @blog.comments.all
    end

    # GET /blogs/new
    def new
      @blog = Blog.new
    end

    # GET /blogs/1/edit
    def edit
      @blog = Blog.find(params[:id])
      render :new
    end

    # POST /blogs
    def create
      blog_params = params.require(:blog).permit(:title, :shortdescription, :description, :published, :image)
      @blog = Blog.new(blog_params)
      if @blog.save
        flash[:notice] = 'You have successfully created the blog'
        redirect_to venblog_blogs_path
      else
        flash.now[:notice] = 'There is an error in your form'
        render :new
      end
    end

    # PATCH/PUT /blogs/1
    def update
      blog_params = params.require(:blog).permit(:title, :shortdescription, :description, :published, :image)
      @blog = Blog.find(params[:id])
      if @blog.update(blog_params)
        flash[:notice] = 'Update Success'
        redirect_to venblog_blogs_url
      else
        flash.now[:notice] = 'Update Have an error'
        render :new
      end
    end

    # DELETE /blogs/1
    def destroy
      flash[:notice] = if Blog.destroy(params[:id])
                        'Delete successfully'
                      else
                        'Error'
                      end
      redirect_to venblog_blogs_url
    end

    # private

    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :shortdescription, :description, :published, :image)
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.permit(:Name, :comment)
    end
  end

end 

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/index.html.erb
<section class="navigation">
  <div class="nav-container">
    <div class="brand">
      <%= link_to root_path do %>
        <%= image_tag("logo1.png", style: 'height:50px; width:50px;') %>
        VenBlog
      <% end %>
    </div>
    <nav>
   <ul class="nav-list">
      <li><%= link_to "CREATE A BLOG", new_blog_path%></li>
  </ul>
   </nav>
  </div>
</section>

<section class="container">
     <%= image_tag("pexels-photo-580900.webp", style: 'width:100%; height:50vh; alt=banner')  %>
</section>
<br>
<br>

<section class="section comments">
  <div class="container">
      <h2 class="subtitle is-5"><strong> The Total Comments <%=  @comments_all.count %></strong> </h2>

      <table class='table'>
        <tr>
          <th>Name</th>
          <th>Short Comment</th>
          <th>Create_at</th>
          <th>Detail</th>
        </tr>
        <% @comments.each do |comment| %>
          <tr>
          <td><%= comment.Name %></td>
          <td><%= comment.comment %></td>
          <td><%= comment.created_at %></td>
          <td><%= link_to "Show this blog", blog_path(@blog) %></td>
          </tr>
        <% end %>
      </table>
  </div>
</section>

<div class="bd-example-snippet bd-code-snippet"><div class="bd-example">
<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
  <div class="btn-group me-2" role="group" aria-label="First group">
    <%= paginate @comments, theme: 'bootstrap-5' %>
  </div>
  </div>
</div>
<br>

app/views/comments/new.html.erb
<section>
  <h2>Add a comment</h2>
  <%= form_for @comments do |form| %>
    <div>
      <%= form.label :text, class: "form-label" %>
      <%= form.text_field :text, required: true, autofocus: true, placeholder: 'Leave a comment', class: "form-input" %>
    </div>
    <%= form.submit "Comment", class: "form-button" %>
  <% end %>
</section>


<div class="box">
  <article class="media">
    <div class="media-content">
        <div class="content">
            <%= form_for @comment do |f| %>
                <%= comment.Name %></strong>
                <%= comment.comment %>

            <% end %>
        </div>
    </div>

    <%= link_to 'Delete', [comment.blog, comment], method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
  </article>
</div>

app/views/comments/show.html.erb
<section class="navigation">
  <div class="nav-container">
    <div class="brand">
      <%= link_to root_path do %>
        <%= image_tag("logo1.png", style: 'height:50px; width:50px;') %>
        VenBlog
      <% end %>
    </div>
    <nav>
   <ul class="nav-list">
      <li><%= link_to "BlOGLIST",venblog_blogs_path %></li>
  </ul>
   </nav>
  </div>
</section>

<section class="container">
     <%= image_tag("pexels-photo-580900.webp", style: 'width:100%; height:50vh; alt=banner')  %>
</section>
<br>
<br>
<section class="section comments">
  <div class="container">
    <h2 class="subtitle is-5"><strong> All Comments </strong> </h2>
    <h4 class="fw-light mb-4 pb-2"> <span class="fst-italic">Total <b><%= Comment.all.count %></b> Comments</span></h4>
    <table class='table'>
    <tr>
      <th>Name</th>
      <th>Short Comment</th>
      <th>Create_at</th>
      <th>Detail</th>
    </tr>
    <% @comments.each do |comment| %>  
      <tr>
      <td><%= comment.Name %></td>
      <td><%= comment.comment.first(20) %></td>
      <td><%= comment.created_at %></td> 
      <td><%= link_to "Show this blog", venblog_blog_path(comment.blog_id) %></td>
      </tr>
    <% end %>
  </table>

  </div>
</section>

<div class="bd-example-snippet bd-code-snippet"><div class="bd-example">
<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
  <div class="btn-group me-2" role="group" aria-label="First group">
    <%= paginate @comments, theme: 'bootstrap-5' %>
  </div>
  </div>
</div>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset='utf-8'>
    <title><%= yield(:page_title) %> | Blog</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC' crossorigin='anonymous'>
    <%= stylesheet_link_tag "application", 'data-turbolinks-track': 'reload', :media => "all" %>
    <%= javascript_include_tag "turbo", 'data-turbolinks-track': 'reload', type: "module" %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Mono&subset=greek">
    <!-- <link href="/assets/stylesheets/application.css.scss" rel="stylesheet"> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/search' %>

        <% flash.each do |name, msg| %>
          <div class='alert alert-success notice' role='alert'>
            <%= content_tag :div, msg, class: name %>
          </div>
        <% end %>

    <main class="container">
      <%= yield %>
    </main>
  </div>

<footer class="footer mt-auto py-3 bg-light">
  <div class="container" style="text-align:center">
    <span class="text-muted">ZigeXn VenTura 2023</span>
  </div>
</footer>

</body>
</html>

app/views/top/index.html.erb
<section class="navigation">
  <div class="nav-container">
    <div class="brand">
      <%= link_to root_path do %>
        <%= image_tag("logo1.png", style: 'height:50px; width:50px;') %>
        VenBlog
      <% end %>
    </div>
    <nav>
   <ul class="nav-list">
      <li><%= link_to "BlOGLIST",venblog_blogs_path %></li>
  </ul>
   </nav>
  </div>
</section>

<section class="container">
     <%= image_tag("pexels-photo-580900.webp", style: 'width:100%; height:50vh; alt=banner')  %>
</section>
<br>
<br>

<div class="count-container">
    <h2 class="subtitle is-5"><strong> Total <%= @blogs.count %></strong> Blogs</h2>
</div>
<%= form_tag root_path, method: :GET, class: 'search-container' do %>
   <div class ='input-group'>
       <div class ='form-outline'>
       <%= text_field_tag :keyword, params[:keyword], class: 'search-bar', placeholder:"What can I help you with today?" %>
       </div>
   <%= submit_tag :search, class: 'btn btn-success' %>
   </div>
<% end %>
<div class="album text-muted">
   <div class="container">
      <div class="row">
         <% @blogs_all.each do |blog| %>
         <div class="card">
         <div class="card-block">
            <div class="card-image"><%= image_tag("#{blog.image}", style: 'height:200px; width:100%; background-size: cover; background-position: center;') %></div>
            <p class="card-title"><%= blog.title %></p>
            <p class="btn btn-info btn-sm" ><%= blog.published ? 'PUBLISHED' : 'UNPUBLISH' %></p>
            <p class="card-create"><%= blog.created_at %></p>
            <p class="card-description"><%= blog.shortdescription %></p>
            <p class="card-comment  ">Comment <%= blog.comments.count %></p>
            <%= link_to "Show this blog", venblog_blog_path(blog), class: 'btn btn-read mt-auto mr-auto' %>
         </div>
         </div>
         <% end %>
      </div>
   </div>
</div>
<div class="bd-example-snippet bd-code-snippet"><div class="bd-example">
<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
  <div class="btn-group me-2" role="group" aria-label="First group">
  <%= paginate @blogs_all, theme: 'bootstrap-5' %>
  </div>
</div></div>
<br><br>
<hr>
<h2 class="subtitle is-5"><strong> The Lastest Blogs </strong> </h2>

<% @lastest_blogs.each do |blog| %>
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <h3 class="mb-0"><%= blog.title %></h3>
          <div class="mb-1 text-muted"><%= blog.created_at %></div>
          <div class="mb-1 text-muted"><strong class="d-inline-block mb-2 text-success"><%= blog.comments.count %> comments </strong> | <%= blog.published ? "PUBLISHED" : "UNPUBLISH" %></div>
          <p class="card-text mb-auto"><%= blog.shortdescription %></p>
          <p><%= link_to "Continue reading", venblog_blog_path(blog) %></p>
        </div>
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img" width="200" height="250"  role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
          <%= image_tag("#{blog.image}", style: 'height:200px; width:200px;') %></svg>
        </div>
      </div>
  <% end %>
  <hr>
  <h2 class="subtitle is-5"><strong> The Lastest Comments </strong> </h2>

  <div class="row d-flex justify-content-start" >
    <% @comments.each do |comment| %>
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
        <h4 mb-0><%= comment.Name %></h4>
        <p class="card-create"><cite title="Source Title"><%= comment.created_at %></cite></p>
        <p><%= comment.comment.first(20) %></p>
        <i><a href="<%= venblog_blog_path(comment.blog) %>#<%= comment.id %>">see more</a></i>
      </div>
    <% end %>
</div>
<br>

app/views/venblog/blogs/_blog.html.erb
<div class="album text-muted">
  <div class="container">
    <div class="row">
       <% @blogs.each do |blog| %>
         <div class="card">
            <div class="card-block">
              <div class="card-image"><%= image_tag("#{blog.image}") %></div>
              <p class="card-title"><%= blog.title %></p>
              <a href="<%= blog_path(blog) %>"><%= image_tag("#{blog.image}", style: 'height:200px; width:200px;') %><a>
              <p class="card-create"><%= blog.created_at %></p>
              <p class='tags'><%= raw blog.tags.map { |t| link_to t.name, venblog_blog_path(tag: t.name) }.join(', ') %></p>
              <p class="card-description"><%= truncate(blog.description), length: {130}/p>
              <p class="card-comment"><%= link_to blog.comments.count , blog_comments_path(blog) %></p>
              <%= link_to "Show this blog", venblog_blog_path(blog) %>
            </div>
         </div>
       <% end %>
    </div>
    <div class="row">
      <div class="col-md-12">
      <%= paginate @blogs, theme: 'bootstrap-5' %>
      </div>
    </div>
  </div>
</div>

app/views/venblog/blogs/_form.html.erb
<%= simple_form_for([:venblog, @blog], data: { turbo: false }) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="grid_container">
  <div class="form-inputs">
    <%= f.input :title, label: 'Title' %>
    <%= f.input :shortdescription, label: 'Short Description' %>
    <%= f.input :description, as: :text %>
    <%= f.input :published %>
    <%= f.file_field :image %>
  </div>
  <br><br>
</div>
 
  <div class="item_submit item_center item_bttm">
    <%= f.button :submit, class: 'btn btn-success btn-block' %>
  </div>
<% end %>

app/views/venblog/blogs/edit.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Edit Blog</h4>
        <%= render "form", blog: @blog %>
      </div>
    </div>
  </div>
</div>
<%= link_to "Show this blog", @blog %>

app/views/venblog/blogs/index.html.erb
<section class="navigation">
  <div class="nav-container">
    <div class="brand">
      <%= link_to root_path do %>
        <%= image_tag("logo1.png", style: 'height:50px; width:50px;') %>
        VenBlog
      <% end %>
    </div>
    <nav>
   <ul class="nav-list">
      <li><%= link_to "CREATE A BLOG", new_venblog_blog_path%></li>
  </ul>
   </nav>
  </div>
</section>

<section class="container">
  <%= image_tag("pexels-photo-580900.webp", style: 'width:100%; height:50vh; alt=banner')  %>
</section>
<br>
<br>

<div class="count-container">
  <h2 class="blog-post-title"><strong> Total <%= @blogs.count %></strong> Blogs</h2>
</div>

<%= form_tag venblog_blogs_path, method: :GET, class: 'search-container' do %>
  <div class ='input-group'>
    <div class ='form-outline'>
      <%= text_field_tag :keyword, params[:keyword], class: 'search-bar', placeholder:"What can I help you with today?" %>
    </div>
    <%= submit_tag :search, class: 'btn btn-success' %>
  </div>
<% end %>
<div class="album text-muted">
  <div class="container">
    <div class="row">
      <% @blogs_all.each do |blog| %>
        <div class="card">
          <div class="card-block">
            <div class="card-image"><%= image_tag("#{blog.image}", style: 'height:200px; width:100%; background-size: cover; background-position: center;') %></div>
            <p class="card-title"><%= blog.title %></p>
            <p class="btn btn-info btn-sm" ><%= blog.published ? 'PUBLISHED' : 'UNPUBLISH' %></p>
            <p class="card-create"><%= blog.created_at %></p>
            <p class="card-description"><%= blog.description %></p>
            <p class="card-comment  ">Comment <%= blog.comments.count %></p>
            <%= link_to "Show this blog", venblog_blog_path(blog), class: 'btn btn-read mt-auto mr-auto' %>
            <%= link_to 'Edit', edit_venblog_blog_path(blog) %>
            <%= link_to 'Delete', venblog_blog_path(blog), data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to detele this blog?' } %>
          </div>
       </div>
      <% end %>
    </div>
  </div>
</div>
<div class="clear_all txt_justify">
  <div class="bd-example-snippet bd-code-snippet"><div class="bd-example">
  <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
    <div class="btn-group me-2" role="group" aria-label="First group">
    <%= paginate @blogs_all, theme: 'bootstrap-5' %>
    </div>
  </div>
  </div>
</div>
<br><br>

app/views/venblog/blogs/new.html.erb
<section class="navigation">
  <div class="nav-container">
    <div class="brand">
      <%= link_to root_path do %>
        <%= image_tag("logo1.png", style: 'height:50px; width:50px;') %>
        VenBlog
      <% end %>
    </div>
    <nav>
      <ul class="nav-list">
        <li><%= link_to "BlOGLIST", venblog_blogs_path %></li>
      </ul>
    </nav>
  </div>
</section>

<section class="container">
  <%= image_tag("pexels-photo-580900.webp", style: 'width:100%; height:50vh; alt=banner')  %>
</section>
<br>
<br>

<h1>Create Blog</h1>

<%= render "form", blog: @blog %>
<br>

app/views/venblog/blogs/show.html.erb
<section class="navigation">
  <div class="nav-container">
    <div class="brand">
      <%= link_to root_path do %>
        <%= image_tag("logo1.png", style: 'height:50px; width:50px;') %>
        VenBlog
      <% end %>
    </div>
    <nav>
      <ul class="nav-list">
        <li><%= link_to "BlOGLIST", venblog_blogs_path %></li>
      </ul>
    </nav>
  </div>
</section>

<section class="container">
  <%= image_tag("pexels-photo-580900.webp", style: 'width:100%; height:50vh; alt=banner')  %>
</section>
<br>
<br>

<article class="blog-post">
  <div class="row">
    <div class="col-md-1 col-lg-2"></div>
      <div class="col-md-10 col-lg-8 text-xs-center">
      <h2 class="blog-post-title"><%= @blog.title %></h2>
      <p class="blog-post-meta"><%= @blog.created_at %></a></p>
      <p><%= @blog.shortdescription %></p>
      <hr>
      <p><%= @blog.description %><</p>
      <div class="card-img"><%= image_tag("#{@blog.image}") %></p></div>
    </div>
  </div>
</article>
<hr>
<h2 class="mb-0">Recent comments</h2>
<h4 class="fw-light mb-4 pb-2"> <span class="fst-italic">Total <b><%= @comments_blog.count %></b> Comments</span></h4>
<% @comments.each do |comment| %>
 
  <div class="list-group w-auto" id="<%= comment.id %>">
    <a href="<%= comment.id %>">
    <a href="<%= blog_comments_path(@blog.id)%>" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
      <div class="d-flex gap-2 w-100 justify-content-between">
        <div>
          <h6 class="mb-0"><%= comment.Name %></h6>
          <p class="mb-0 opacity-75"><%= comment.comment %></p>
        </div>
        <small class="opacity-50 text-nowrap"> <%= comment.created_at %></small>
      </div>
    </a>
    <% end %>
  </div>
  <br>
  <div class="bd-example-snippet bd-code-snippet"><div class="bd-example">
    <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
      <div class="btn-group me-2" role="group" aria-label="First group">
        <%= paginate @comments, theme: 'bootstrap-5' %>
      </div>
      </div>
    </div>
  
  <hr>
  <h2> Leave a Comment </h2>
  <%= form_for([@blog, Comment.new], method: :POST) do |f| %>
    <%= f.label :Name %><br>
    <%= f.text_field :Name %><br>

    <%= f.label :comment %><br>
    <%= f.text_area :comment %><br>

  <%= f.submit %>
<% end %>
<br>